# Generated by Django 6.0.5 on 2026-06-03 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gamelibrary_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='releaseyear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
